baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Sundog Farmstead'
theme = "spectral"

[params]
fancyTitle = "Sundog Farmstead"
copyright = "sundog Farmstead"
description = "queer-run flex-farming and mindful<br /> agruculture in midcoast maine"
startbuttonText = "contact"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "main.css"

[menu]
[[menu.main]]
  name = "home"
  url = '/'
  title = "Home"
[[menu.main]]
  identifier = "training"
  url = "/training/"
  name="Training"
[[menu.main]]
  url = '/posts/'
  name = "Posts"
  parent = "training"
  identifier = "posts"
  pre = "◇"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.one.icon]]
icon = "fa-paw"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-paw"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "Waldoboro, Maine"
email = "xx@gmail.com"
subject = "Sundog Contact"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"